IMG_SHAPE: [40, 40, 1]
LATENT_DIM: 100
NUM_CLASSES: 9
BATCH_SIZE: 256
EPOCHS: 5000
LR: 0.0002
BETA_1: 0.5

early_stopping:
  enabled: true
  patience: 5         # Stop if no FID improvement for 5 intervals (e.g., 500 epochs if interval is 100)
  monitor_metric: fid # Can also be "classifier_acc" in future
