# === DATA CONFIG ===
IMG_SHAPE: [40, 40, 1]
NUM_CLASSES: 9
LATENT_DIM: 100
BATCH_SIZE: 256
EPOCHS: 5
PATIENCE: 10


# === OPTIMIZER CONFIG ===
LR: 0.0002
BETA_1: 0.5  # For Adam optimizer

# === VAE CONFIG ===
BETA_KL: 1.0  # beta-VAE (1.0 = standard VAE)

# === DIFFUSION CONFIG ===
TIMESTEPS: 1000
T: 1000  # Optional override for number of noise steps

# === EARLY STOPPING ===
early_stopping:
  enabled: true
  patience: 5         # Stop if no metric improvement
  monitor_metric: fid # Options: "fid", "classifier_acc", "val_loss"

# === GENERAL MODE SELECTION ===
mode: train  # Options: train, eval_only, sample_only

# === AUTOREGRESSIVE CONFIG ===
AR:
  temperature: 1.0    # Sampling temperature
  max_len: 1600       # Max pixel generation steps for flattened 40x40
  embedding_dim: 128  # Embedding dimension for pixels + labels

model:
  num_flow_layers: 5

